### ISSUE TITLE
Disconnect

### ISSUE THREAD

**Issue by ch315929** [cortexm/pyswd#11]
Is there a way to disconnect the Swd interface?

**Comment by schneidersoft** [comment]
I found that I had to use something like this to make it possible to reconnect
```
dev = swd.Swd()
del dev
...
dev = swd.Swd()
```

one cool thing is that swd doesn't try to reset the device unless you tell it to. Cool because it means you can leave the MCU in reset!
A 'proper' disconnect was something like this for me:
```
dev = swd.Swd()
...
swd.CortexM(dev).reset()
del dev
```
might be related?

**Comment by pavelrevak** [comment]
yes, `del` command will work
