### ISSUE TITLE
No backend available

### ISSUE THREAD

**Issue by Tomsiik** [cortexm/pyswd#13]
Hello, How to install properly? 
I run under Windows.
I've installed packages pyswd 1.0.0 and pyusb 1.1.1 by just "pip install pyswd" command. When I run python and after import swd package, firstly I try to initialize by "dev = swd.Swd()" I get error "No backend available".

Please help me.

**Comment by pavelrevak** [comment]
Hello Tomas, first you need to have properly installed libusb, (it is dependency of pysusb)
then it it should work

**Comment by Tomsiik** [comment]
Do you have step by step guide how to install properly libusb on Windows? I've try Zadiq, copy dll to system32 ,.. not succesful.

**Comment by pavelrevak** [comment]
try this: https://github.com/pavelrevak/pystlink#requirements

**Comment by Tomsiik** [comment]
Thank you, it works. I have another question. I use a device that gets to the standby mode, before it in devices sw is some delay after HW reset for connection of debug probe - it works for j-link but doesn't work for st-link. 
Can your package reset HW over the reset pin of swd/jtag connector such as J-Link?

**Comment by pavelrevak** [comment]
Well,
Yes, no external reset control is currently implemented (not too hard, but no time for this).
But, there is a way, you can:
1. manually ground reset pin (enter MCU reset)
2. run command: `pyswd reset:halt`
3. leave reset
4. and you are in running MCU, and program is halted before run..

If you need more support, you can write me email to pavelrevak at gmail, also in czech
