### ISSUE TITLE
Cannot find ST Link 

### ISSUE THREAD

**Issue by Masitech** [cortexm/pyswd#15]
Using the PyUSB I was able to find the ST link however having issues with the pyswd. 
![image](https://user-images.githubusercontent.com/18357986/123417682-f9179f00-d5af-11eb-958b-6cddc168947b.png)
![image](https://user-images.githubusercontent.com/18357986/123417565-d2596880-d5af-11eb-9ef9-b9248e18a70b.png)

**Comment by pavelrevak** [comment]
fixed in 242a065
