### ISSUE TITLE
Usage of read_mem and write_mem

### ISSUE THREAD

**Issue by MrMfromK** [cortexm/pyswd#21]
I wonder if read_mem and write_mem with the suffixes 8, 16, 32 all use and store data in bytes.
So what memory view do I get for write_mem32 (0x20000000, [1, 2, 3, 4])?
01 00 00 00 02 00 00 00 03 00 00 00 04 00 00 00  = interpreting data as 32 bit values?
01 02 03 04 00 00 00 00 00 00 00 00 00 00 00 00 = interpreting data as 8 bit values but write them in 32 bit accesses?
The same reverse for read_memX
It seems, that data is always in bytes (??) Is there a way to get 32bit data in and out or must I do the processing on my own?

**Comment by pavelrevak** [comment]
you can put there bytes or bytearray... converting 32bit number into bytes:
```python
number = 0x1234
write_mem32(0x20000000, number.to_bytes(4, 'little'))
```
will write: `34 12 00 00`

write_memX always eat bytes, but use different access to memory, where mem8 write each byte separatelly, mem32 write 32bit number at once.
